steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args:
  - 'build'
  - '--tag'
  - 'gcr.io/monketer-website/monketer-app'
  - '--build-arg'
  - '_VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
  - '--build-arg'
  - '_VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
  - '--build-arg'
  - '_VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
  - '--build-arg'
  - '_VITE_PUBLIC_STRIPE_PRO_PRICE_ID=${_VITE_PUBLIC_STRIPE_PRO_PRICE_ID}'
  - '--build-arg'
  - '_VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID=${_VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID}'
  - '.'
  secretEnv:
  - 'VITE_SUPABASE_URL'
  - 'VITE_SUPABASE_ANON_KEY'
  - 'VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY'
  - 'VITE_PUBLIC_STRIPE_PRO_PRICE_ID'
  - 'VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/monketer-website/monketer-app']

# Deploy container image to Cloud Run, referencing the new image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'monketer-app'
  - '--image'
  - 'gcr.io/monketer-website/monketer-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/monketer-website/monketer-app'

availableSecrets:
  secretManager:
  - versionName: projects/913896969230/secrets/VITE_SUPABASE_URL/versions/latest
    env: 'VITE_SUPABASE_URL'
  - versionName: projects/913896969230/secrets/VITE_SUPABASE_ANON_KEY/versions/latest
    env: 'VITE_SUPABASE_ANON_KEY'
  - versionName: projects/913896969230/secrets/VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY/versions/latest
    env: 'VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY'
  - versionName: projects/913896969230/secrets/VITE_PUBLIC_STRIPE_PRO_PRICE_ID/versions/latest
    env: 'VITE_PUBLIC_STRIPE_PRO_PRICE_ID'
  - versionName: projects/913896969230/secrets/VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID/versions/latest
    env: 'VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID'

options:
  logging: CLOUD_LOGGING_ONLY 