steps:
# Authorize Cloud Build to access secrets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=VITE_SUPABASE_URL > /workspace/VITE_SUPABASE_URL
    gcloud secrets versions access latest --secret=VITE_SUPABASE_ANON_KEY > /workspace/VITE_SUPABASE_ANON_KEY
    gcloud secrets versions access latest --secret=VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY > /workspace/VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY
    gcloud secrets versions access latest --secret=VITE_PUBLIC_STRIPE_PRO_PRICE_ID > /workspace/VITE_PUBLIC_STRIPE_PRO_PRICE_ID
    gcloud secrets versions access latest --secret=VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID > /workspace/VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args:
  - 'build'
  - '--tag'
  - 'gcr.io/monketer-website/monketer-app'
  - '--build-arg'
  - 'VITE_SUPABASE_URL=$(cat /workspace/VITE_SUPABASE_URL)'
  - '--build-arg'
  - 'VITE_SUPABASE_ANON_KEY=$(cat /workspace/VITE_SUPABASE_ANON_KEY)'
  - '--build-arg'
  - 'VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(cat /workspace/VITE_PUBLIC_STRIPE_PUBLISHABLE_KEY)'
  - '--build-arg'
  - 'VITE_PUBLIC_STRIPE_PRO_PRICE_ID=$(cat /workspace/VITE_PUBLIC_STRIPE_PRO_PRICE_ID)'
  - '--build-arg'
  - 'VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID=$(cat /workspace/VITE_PUBLIC_STRIPE_PREMIUM_PRICE_ID)'
  - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/monketer-website/monketer-app']

# Deploy container image to Cloud Run, referencing the new image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'monketer-app'
  - '--image'
  - 'gcr.io/monketer-website/monketer-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/monketer-website/monketer-app'

options:
  logging: CLOUD_LOGGING_ONLY 