/**
 * Helper function to clean UUIDs that might have spaces or comments.
 * Often needed for IDs generated by AI.
 */
export function cleanUuid(id: string): string {
  if (!id || typeof id !== 'string') return ''; // Add type check
  
  // Remove any trailing digits or spaces
  const cleaned = id.replace(/\s+\d*$/, '').trim();
  
  // If it looks like a UUID, return it; otherwise return as is
  // Consider if non-UUIDs should be allowed or generate a new one?
  const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (uuidPattern.test(cleaned)) {
    return cleaned;
  }
  
  // If it doesn't look like a UUID, maybe log a warning or return original trimmed?
  // console.warn(`[cleanUuid] Input ID "${id}" doesn't look like a valid UUID after cleaning.`);
  // Avoid console logs in generic lib functions unless specifically for debugging
  return id.trim(); // Return original trimmed ID if not UUID-like
}

// Add other UUID related utilities here if needed in the future 