[functions]
[functions.generate-email-changes]
verify_jwt = true

[functions.manage-pending-changes]
verify_jwt = true

[functions.send-preview-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-preview-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-preview-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-preview-email/*.html" ]
